#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.Utilidades.GuardaErrores
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_A6B512_dmatarrita2")]
	public partial class ErroresDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ErroresDataContext() : 
				base(global::Capa.Utilidades.Properties.Settings.Default.DB_A6B512_dmatarrita2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ErroresDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ErroresDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ErroresDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ErroresDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarErrorLog")]
		public int sp_InsertarErrorLog([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MetodoError", DbType="VarChar(300)")] string metodoError, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Clase", DbType="VarChar(60)")] string clase, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorReportado", DbType="VarChar(400)")] string errorReportado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LineaError", DbType="VarChar(400)")] string lineaError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), metodoError, clase, errorReportado, lineaError);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
