#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa.AccesoDatos.SQLLinqCarritoCompras
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_A6B512_dmatarrita2")]
	public partial class CarritoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CarritoDataContext() : 
				base(global::Capa.AccesoDatos.Properties.Settings.Default.DB_A6B512_dmatarrita2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertarErrorLog")]
		public int sp_InsertarErrorLog([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MetodoError", DbType="VarChar(300)")] string metodoError, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Clase", DbType="VarChar(60)")] string clase, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ErrorReportado", DbType="VarChar(400)")] string errorReportado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LineaError", DbType="VarChar(400)")] string lineaError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), metodoError, clase, errorReportado, lineaError);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtieneProductosPorCategoria")]
		public ISingleResult<sp_ObtieneProductosPorCategoriaResult> sp_ObtieneProductosPorCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria);
			return ((ISingleResult<sp_ObtieneProductosPorCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ObtieneProductos")]
		public ISingleResult<sp_ObtieneProductosResult> sp_ObtieneProductos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ObtieneProductosResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_ObtieneProductosPorCategoriaResult
	{
		
		private int _IdProducto;
		
		private string _NombreProducto;
		
		private string _DescripcionProducto;
		
		private decimal _PrecioProducto;
		
		private string _ImagenProducto;
		
		private int _IdCategoria;
		
		public sp_ObtieneProductosPorCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionProducto", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DescripcionProducto
		{
			get
			{
				return this._DescripcionProducto;
			}
			set
			{
				if ((this._DescripcionProducto != value))
				{
					this._DescripcionProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProducto", DbType="Decimal(18,2) NOT NULL")]
		public decimal PrecioProducto
		{
			get
			{
				return this._PrecioProducto;
			}
			set
			{
				if ((this._PrecioProducto != value))
				{
					this._PrecioProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenProducto", DbType="VarChar(MAX)")]
		public string ImagenProducto
		{
			get
			{
				return this._ImagenProducto;
			}
			set
			{
				if ((this._ImagenProducto != value))
				{
					this._ImagenProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
	}
	
	public partial class sp_ObtieneProductosResult
	{
		
		private int _IdProducto;
		
		private string _NombreProducto;
		
		private string _DescripcionProducto;
		
		private decimal _PrecioProducto;
		
		private string _ImagenProducto;
		
		private int _IdCategoria;
		
		public sp_ObtieneProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionProducto", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DescripcionProducto
		{
			get
			{
				return this._DescripcionProducto;
			}
			set
			{
				if ((this._DescripcionProducto != value))
				{
					this._DescripcionProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProducto", DbType="Decimal(18,2) NOT NULL")]
		public decimal PrecioProducto
		{
			get
			{
				return this._PrecioProducto;
			}
			set
			{
				if ((this._PrecioProducto != value))
				{
					this._PrecioProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagenProducto", DbType="VarChar(MAX)")]
		public string ImagenProducto
		{
			get
			{
				return this._ImagenProducto;
			}
			set
			{
				if ((this._ImagenProducto != value))
				{
					this._ImagenProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
