<?xml version="1.0" encoding="utf-8"?><Database Name="DB_A6B512_dmatarrita2" Class="CarritoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql5086.site4now.net;Initial Catalog=DB_A6B512_dmatarrita2;Persist Security Info=True;User ID=DB_A6B512_dmatarrita2_admin;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="Capa.AccesoDatos.Properties.Settings" SettingsPropertyName="DB_A6B512_dmatarrita2ConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_InsertarErrorLog" Method="sp_InsertarErrorLog">
    <Parameter Name="MetodoError" Parameter="metodoError" Type="System.String" DbType="VarChar(300)" />
    <Parameter Name="Clase" Parameter="clase" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="ErrorReportado" Parameter="errorReportado" Type="System.String" DbType="VarChar(400)" />
    <Parameter Name="LineaError" Parameter="lineaError" Type="System.String" DbType="VarChar(400)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ObtieneProductosPorCategoria" Method="sp_ObtieneProductosPorCategoria">
    <Parameter Name="IdCategoria" Parameter="idCategoria" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ObtieneProductosPorCategoriaResult">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreProducto" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionProducto" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioProducto" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ImagenProducto" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ObtieneProductos" Method="sp_ObtieneProductos">
    <ElementType Name="sp_ObtieneProductosResult">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreProducto" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionProducto" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioProducto" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ImagenProducto" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_InsertarCarritoPorCliente" Method="sp_InsertarCarritoPorCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ActualizarCarritoPorCliente" Method="sp_ActualizarCarritoPorCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarCarritoPorCliente" Method="sp_EliminarCarritoPorCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ObtieneCarritoPorCliente" Method="sp_ObtieneCarritoPorCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ObtieneCarritoPorClienteResult">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreProducto" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ImagenProducto" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DescripcionProducto" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioProducto" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ActualizarDatosCliente" Method="sp_ActualizarDatosCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertarDatosCliente" Method="sp_InsertarDatosCliente">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Contrasena" Parameter="contrasena" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ObtieneDatosClientePorCliente" Method="sp_ObtieneDatosClientePorCliente">
    <Parameter Name="IdCliente" Parameter="idCliente" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ObtieneDatosClientePorClienteResult">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>